"use client";

import { useMemo, useState } from "react";

import { ClockIcon, FlagIcon, TagIcon } from "@/components/icons";
import { TaskChip } from "@/components/task/TaskChip";
import { LABEL_COLORS } from "@/lib/labels";
import { TAGS, type Tag, type Task } from "@/lib/types";
import { PRIORITY_RANK } from "@/store/createAppStore";
import { useAppStore } from "@/store/StoreProvider";

import styles from "./FiltersView.module.css";
import view from "./View.module.css";

type FilterKey = "priority" | "deadline" | "tag";

const FILTERS: Array<{
  key: FilterKey;
  name: string;
  note: string;
  Icon: typeof FlagIcon;
}> = [
  { key: "priority", name: "Priority", note: "High-priority first", Icon: FlagIcon },
  { key: "deadline", name: "Deadline", note: "Sorted by due date", Icon: ClockIcon },
  { key: "tag", name: "By smart tag", note: "Grouped by label", Icon: TagIcon },
];

export function FiltersView() {
  const today = useAppStore((s) => s.today);
  const allTasks = useAppStore((s) => s.tasks);

  const [activeFilter, setActiveFilter] = useState<FilterKey | null>(null);
  const [activeTag, setActiveTag] = useState<Tag | null>(null);

  const open = useMemo(
    () => allTasks.filter((t) => t.status !== "done"),
    [allTasks],
  );

  /** Counts shown on the right of each filter card. */
  const counts = useMemo(
    () => ({
      priority: open.filter((t) => t.priority === "high").length,
      deadline: open.filter((t) => t.deadline).length,
      tag: new Set(open.flatMap((t) => t.tags)).size,
    }),
    [open],
  );

  const labelCounts = useMemo(() => {
    const map = Object.fromEntries(TAGS.map((t) => [t, 0])) as Record<Tag, number>;
    for (const task of open) {
      for (const tag of task.tags) map[tag] += 1;
    }
    return map;
  }, [open]);

  const results = useMemo<Task[]>(() => {
    if (activeTag) return open.filter((t) => t.tags.includes(activeTag));
    if (activeFilter === "priority") {
      return [...open].sort(
        (a, b) => PRIORITY_RANK[a.priority] - PRIORITY_RANK[b.priority],
      );
    }
    if (activeFilter === "deadline") {
      return open
        .filter((t) => t.deadline)
        .sort((a, b) => (a.deadline ?? "").localeCompare(b.deadline ?? ""));
    }
    if (activeFilter === "tag") {
      return [...open].sort((a, b) =>
        (a.tags[0] ?? "").localeCompare(b.tags[0] ?? ""),
      );
    }
    return [];
  }, [activeFilter, activeTag, open]);

  const toggleFilter = (key: FilterKey) => {
    setActiveTag(null);
    setActiveFilter((current) => (current === key ? null : key));
  };

  const toggleTag = (tag: Tag) => {
    setActiveFilter(null);
    setActiveTag((current) => (current === tag ? null : tag));
  };

  const resultLabel = activeTag
    ? `${activeTag} · ${results.length}`
    : FILTERS.find((f) => f.key === activeFilter)?.name;

  return (
    <div className={`${view.view} ${view.viewWide}`}>
      <h1 className={view.h1}>Filters &amp; labels</h1>

      <section className={view.section}>
        <h2 className={view.sectionLabelMuted}>My filters</h2>
        <div className={view.list}>
          {FILTERS.map(({ key, name, note, Icon }) => (
            <button
              key={key}
              type="button"
              className={styles.filterCard}
              data-active={activeFilter === key || undefined}
              onClick={() => toggleFilter(key)}
              aria-pressed={activeFilter === key}
            >
              <span className={styles.filterIcon}>
                <Icon size="1.125rem" />
              </span>
              <span className={styles.filterText}>
                <span className={styles.filterName}>{name}</span>
                <span className={styles.filterNote}>{note}</span>
              </span>
              <span className={styles.filterCount}>{counts[key]}</span>
            </button>
          ))}
        </div>
      </section>

      <section className={view.section}>
        <div className={view.sectionHead}>
          <h2 className={view.sectionLabelMuted}>Labels</h2>
          <span className={view.sectionNote}>auto-generated by Cerno</span>
        </div>
        <div className={styles.labelPills}>
          {TAGS.map((tag) => (
            <button
              key={tag}
              type="button"
              className={styles.labelPill}
              data-active={activeTag === tag || undefined}
              onClick={() => toggleTag(tag)}
              aria-pressed={activeTag === tag}
            >
              <span
                className={styles.labelDot}
                style={{ background: LABEL_COLORS[tag] }}
              />
              <span className={styles.labelName}>{tag}</span>
              <span className={styles.labelCount}>{labelCounts[tag]}</span>
            </button>
          ))}
        </div>
      </section>

      {(activeFilter || activeTag) && (
        <section className={view.section}>
          <h2 className={view.sectionLabelSmall}>{resultLabel}</h2>
          {results.length > 0 ? (
            <div className={view.listTight}>
              {results.map((task) => (
                <TaskChip key={task.id} task={task} today={today} />
              ))}
            </div>
          ) : (
            <p className={view.emptyDashed}>Nothing matches this filter.</p>
          )}
        </section>
      )}
    </div>
  );
}
